// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UUID } from '@opencrvs/commons'
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely'

/** Represents the table app.user_offices */
export default interface UserOfficesTable {
  userId: ColumnType<UUID, UUID, UUID>

  officeId: ColumnType<UUID, UUID, UUID>
}

export type UserOffices = Selectable<UserOfficesTable>

export type NewUserOffices = Insertable<UserOfficesTable>

export type UserOfficesUpdate = Updateable<UserOfficesTable>
